### ISSUE TITLE
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component

### ISSUE THREAD

**Issue by chinaljs** [jitwxs/express#1]
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.apache.catalina.authenticator.AuthenticatorBase.startInternal(AuthenticatorBase.java:1178)

The following method did not exist:

    javax.servlet.ServletContext.getVirtualServerName()Ljava/lang/String;

The method's class, javax.servlet.ServletContext, is available from the following locations:

    jar:file:/C:/Program%20Files/Java/jdk1.8.0_121/jre/lib/ext/servlet-api.jar!/javax/servlet/ServletContext.class
    jar:file:/D:/Maven/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.17/tomcat-embed-core-9.0.17.jar!/javax/servlet/ServletContext.class

It was loaded from the following location:

    file:/C:/Program%20Files/Java/jdk1.8.0_121/jre/lib/ext/servlet-api.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of javax.servlet.ServletContext

**Comment by jitwxs** [comment]
i think that is your environment question, not related to the project.
