### ISSUE TITLE
sys_user插入数据失败，希望作者大大能够回复

### ISSUE THREAD

**Issue by Xutttt** [jitwxs/express#11]
![123333](https://user-images.githubusercontent.com/90440231/139077210-340912e3-31fd-4c5a-86d4-2967d75408ba.png)

**Comment by 731016** [comment]
`INSERT INTO `sys_user` VALUES ('1', 'user1', '$2a$10$lqib8LGGEziYYaJMmnQ4XubOugCjECjtLHb4yJLgZ.0wDwSjh09Yi', 3, NULL, -1, '1', '1', '123', '17623014429', '2032', 0, NULL, 1,'0', NULL,'2019-04-17 23:10:21', '2019-05-04 14:11:24'),('4139cb9237a7852e694f3569b9030b2c', 'admin1', '$2a$10$lqib8LGGEziYYaJMmnQ4XubOugCjECjtLHb4yJLgZ.0wDwSjh09Yi', 1, NULL, 1, '拉布拉多', '440102198001021230', '777777777', NULL, '1367', 0, NULL, 1,'0', NULL, '2019-05-03 02:03:48', '2019-05-03 15:17:02'), ('77d014e9455b27c0696eb9f969f87912', 'user2', '$2a$10$lqib8LGGEziYYaJMmnQ4XubOugCjECjtLHb4yJLgZ.0wDwSjh09Yi', 3, NULL, 1, NULL, NULL, '2222', NULL, '1382', 0, NULL,'0', 1, NULL, NULL, '2019-05-03 14:49:25'),('f10960e7392847a2c691ad066e2a87c4', 'courier1', '$2a$10$lqib8LGGEziYYaJMmnQ4XubOugCjECjtLHb4yJLgZ.0wDwSjh09Yi', 2, NULL, 1, 'zhangsan', '12345', '11', NULL, '0', 0, NULL, 1, '0', NULL, '2019-04-22 01:10:24', '2019-05-04 14:12:26');`我只留了三个用户，这个有效

**Comment by jitwxs** [comment]
已处理，https://github.com/jitwxs/express/commit/bce8b83def5795c5f3a9feef76cea70007a15b6f
