### ISSUE TITLE
在登录以后绑定人脸的时候弹不出模态框

### ISSUE THREAD

**Issue by Xutttt** [jitwxs/express#14]
提示
info:442 Uncaught ReferenceError: error is not defined
    at startCamera (info:442:76)
    at showModel (info:343:21)
    at HTMLButtonElement.onclick (info:98:110)

在admin文件下的info页面  上网搜索显示好像是jquery的包导入错误
![JN69{0`8%8C3}B(0Q84WN2I](https://user-images.githubusercontent.com/90440231/157054015-35a9e42b-e16f-4515-82cf-6716fdd319cc.png)

**Comment by Xutttt** [comment]
![image](https://user-images.githubusercontent.com/90440231/157055118-e9be68bf-7ebd-4a01-a776-998ef9bc61b5.png)

**Comment by jitwxs** [comment]
使用的是哪一款浏览器和版本号，Chrone 97 版本验证正常

**Comment by Xutttt** [comment]
今天检查Chrone版本的时候也是97，查看版本的时候浏览器自动最新版本了然后就可以正常使用了，现在已经完美解决了，感谢作者大大在百忙之中抽出时间来对我的疑问提出回复！辛苦了！

**Comment by jitwxs** [comment]
> 今天检查Chrone版本的时候也是97，查看版本的时候浏览器自动最新版本了然后就可以正常使用了，现在已经完美解决了，感谢作者大大在百忙之中抽出时间来对我的疑问提出回复！辛苦了！

不客气
