### ISSUE TITLE
templates/user/info.html:54 更正

### ISSUE THREAD

**Issue by mimajiushi** [jitwxs/express#2]
应改为：
<p class="form-control-static col-md-7" id="sex" th:text="${info.sex == '1'? '男':'女'}">未知</p>
后台传过来的是字符串，不是int

**Comment by mimajiushi** [comment]
`<p class="form-control-static col-md-7" id="sex" th:text="${info.sex == '1'? '男':'女'}">未知</p>`

**Comment by jitwxs** [comment]
已更正
